rc/cms/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.base import TemplateView
from rc.cms.views import PageView

urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='cms/index.html'),
        name='resource-center-index'),
    url(r'^(?P<slug>.+)/$', PageView.as_view()),
    )

rc/resources/apps/officers/urls.py
from django.conf.urls.defaults import patterns, url
from rc.resources.apps.officers.models import *
from rc.resources.apps.officers.views import *

urlpatterns = patterns('',
    # url(r'^directory-campus-sustainability-officers$', OfficerList.as_view(template_name = 'officers/directory.html'), name="officers-directory"),
   url(r'^directory-campus-sustainability-officers$',
       ResourceItemListView.as_view(
           model=CampusSustainabilityOfficer,
           queryset=CampusSustainabilityOfficer.objects.order_by(
                   'organization__name')),
       name='officer-directory',
       kwargs={'member_only': True}),
    )

rc/resources/apps/pae/urls.py
from django.conf.urls.defaults import patterns, url

from rc.resources.views import ResourceItemListView
from rc.resources.apps.pae import models
from rc.resources.apps.pae.views import StudentFeeListView


urlpatterns = patterns('',

    url(r'^alumni-sustainability-funds$',
        ResourceItemListView.as_view(
            model=models.AlumniFund,
            queryset=models.AlumniFund.objects.published().order_by('organization__name')),
        name='alumni-funds',
        kwargs={'member_only': True}),

    url(r'^master-plans-incorporate-sustainability$',
        ResourceItemListView.as_view(
            model=models.MasterPlan,
            queryset=models.MasterPlan.objects.published().order_by(
                    'minor_reference_only', 'organization__name')),
        name='master-plans',
        kwargs={'member_only': True, 'title': 'Campus Master Plans that Incorporate Sustainability'}),

    url(r'^campus-sustainability-assessment-tools$',
        ResourceItemListView.as_view(
            model=models.AssessmentTool,
            queryset=models.AssessmentTool.objects.published().order_by(
                    'provider', 'organization__name')),
        name='assessment-tools',
        kwargs={'member_only': True,
         'type_list': dict(models.AssessmentTool.CREATORS)}),

    url(r'^campus-sustainability-blogs$',
        ResourceItemListView.as_view(
            model=models.SustainabilityBlog,
            queryset=models.SustainabilityBlog.objects.published().order_by(
                    'type', 'title')),
        name='sustainability-blogs',
        kwargs={'member_only': True}
        ),

    url(r'^campus-sustainability-plans$',
        ResourceItemListView.as_view(
            model=models.SustainabilityPlan,
            queryset=models.SustainabilityPlan.objects.published().order_by(
                    'organization__name')),
        name='sustainability-plans',
        kwargs={'member_only': True}),

    # url(r'^campus-sustainability-revolving-loan-funds',
    #     ResourceItemListView.as_view(
    #         model=models.RevolvingLoanFund,
    #         queryset=models.RevolvingLoanFund.objects.published().order_by(
    #                 'organization__name', 'title')),
    #     name='revolving-loan-funds',
    #     kwargs={'title': 'Campus Sustainability Revolving Loan Funds',
    #             'member_only': True}),

    url(r'^mandatory-student-fees-renewable-energy-and-energy-efficiency$',
        StudentFeeListView.as_view(
            model=models.StudentFeesDescription,
            queryset=models.StudentFee.objects.published().order_by(
                    'organization__name')),
        name='student-fees',
        kwargs={
            'member_only': True,
            'title': 'Dedicated Student Fees for Sustainability'}
    ),

    )

rc/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from aashe import moderation
from aashe.aasheauth.forms import LoginForm


admin.autodiscover()

moderation.auto_discover()

urlpatterns = patterns(
    '',
    (r'^admin/linkcheck/', include('linkcheck.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^moderation/', include('aashe.moderation.urls')),
    url(r'^campus-sustainability-revolving-loan-funds/',
        include('rc.resources.apps.revolving_fund.urls')),
    url(r'^accounts/login/$', 'aashe.aasheauth.views.login',
        {'template_name': 'auth/login.html',
         'authentication_form': LoginForm},
        name='accounts-login'),
    url(r'^accounts/logout/$', 'aashe.aasheauth.views.logout_then_login',
        {'login_url': reverse_lazy('accounts-login')},
        name='accounts-logout'),
    url(r'^academic-programs/', include('rc.resources.apps.academic_programs.urls')),
    url(r'^green-funds/', include('rc.resources.apps.greenfunds.urls')),
    ('', include('rc.resources.apps.education.urls')),
    ('', include('rc.resources.apps.operations.urls')),
    ('', include('rc.resources.apps.pae.urls')),
    ('', include('rc.resources.apps.policies.urls')),
    ('', include('rc.resources.apps.programs.urls')),
    ('', include('rc.resources.apps.officers.urls')),
    ('', include('rc.cms.urls')),    
)

rc/resources/apps/academic_programs/models.py
from gettext import gettext as _
from django.db import models
from geopy import geocoders
from aashe.organization.models import Organization
from aashe.disciplines.models import Discipline
from aashe.utils.slugify import unique_slugify

# Commitment
COMMITMENT_CHOICES = (
    ('FT', 'Full-time'),
    ('PT', 'Part-time'),
    ('BT', 'Both')
)
# Distance Ed
DISTANCE_CHOICES = (
    ('LO', 'Local-only'),
    ('DT', 'Distance-education'),
    ('BT', 'Both')
)

# Create your models here.
class AcademicProgram(models.Model):
    title = models.CharField(_('program name'), max_length=255)
    institution = models.ForeignKey("organization.Organization", 
                                  help_text="Select the institution or organization that offers this program \
                                  If you need to list more, use the space below.", blank=True, null=True)
    other_inst = models.TextField(_('other institutions'), 
                                  help_text='List any institutions not found in the above list.', blank=True)
    description = models.TextField(verbose_name='Program Description', 
                                   help_text="Briefly describe the program in 500 words or less.", blank=True)
    location_name = models.CharField(max_length=255, 
                                     help_text="e.g. a campus or place of business", blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=6, verbose_name='State/Province',
                             help_text='Two character abbreviation', blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    country = models.CharField(max_length=255, blank=True)
    slug = models.SlugField(max_length=255, editable=False)
    program_type = models.ForeignKey("ProgramType")
    homepage = models.URLField(max_length=255, 
                               help_text="Enter the URL for the program's website.")
    department = models.CharField(max_length=200, 
                                  help_text="Enter the full name(s) of the department(s) that administer this program, if applicable.",
                                  blank=True)
    duration = models.CharField(max_length=255, 
                                help_text='Enter the amount of time typically required to complete this \
                                program (e.g. "4 years with summers off", "2 years with a summer project \
                                between years 1 and 2", "3 months", or "1 week").', blank=True)
    founded = models.CharField(max_length=200, verbose_name='Year Founded',
                             help_text='Enter the year (YYYY) in which the program was created.', blank=True)
    distance_ed = models.CharField(choices=DISTANCE_CHOICES,
                                         max_length=5,
                                         help_text='Is this a distance education program?')
    commitment = models.CharField(choices=COMMITMENT_CHOICES,
                                         max_length=5,
                                         help_text='Is this program full time, part-time, or both?')
    language = models.CharField(max_length=150,
                                help_text="What is this program's primary language of instruction?",
                                blank=True)
    blog = models.URLField(max_length=300, 
                           help_text="Enter the URL for the program's blog, if applicable.",
                           blank=True)
    linkedin = models.URLField(max_length=300, 
                               help_text="Enter the URL for the program's LinkedIn page, if applicable.",
                               blank=True)
    facebook = models.URLField(max_length=300, 
                               help_text="Enter the URL for the program's Facebook page, if applicable.",
                               blank=True)
    twitter = models.URLField(max_length=300,
                              help_text="Enter the URL for the program's Twitter page, if applicable.",
                              blank=True)
    discipline = models.ForeignKey("disciplines.Discipline", 
                                   help_text="Select the discipline or field that best describes \
                                   the approach and focus of this program.")
    project_contact1_firstname = models.CharField(blank=True, max_length=75,
                                                  verbose_name='First name')
    project_contact1_middle = models.CharField(blank=True, max_length=75,
                                               verbose_name='Middle name/initial')
    project_contact1_lastname = models.CharField(blank=True, max_length=75,
                                                 verbose_name='Last name')
    project_contact1_email = models.EmailField(blank=True, verbose_name='Email')
    project_contact1_title = models.CharField(blank=True, max_length=75,
                                              verbose_name='Title/Position')
    project_contact1_phone = models.CharField(blank=True, max_length=75,
                                              verbose_name='Phone')
    project_contact1_department = models.CharField(blank=True, max_length=75,
                                                   verbose_name='Department')
    project_contact1_confirm = models.BooleanField(
        verbose_name='Confirm permission',
        help_text='Check this box to confirm you have obtained permission to provide this contact information.')
    published = models.BooleanField(_("is published"), blank=True)
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    updated_date = models.DateTimeField(auto_now=True, editable=False)
    
    def project_contact1_details(self):
        if not self.project_contact1_firstname:
            return None
        name = u'%s %s' % (self.project_contact1_firstname, self.project_contact1_lastname)
        if self.project_contact1_title:
            name += u', %s' % self.project_contact1_title
        return name
    
    def save(self, *args, **kwargs):
            # create a slug
            if not self.slug:
              unique_slugify(self, '%s' % (self.title))
            # if there's no city, state, or country given, use the institution's
            if not self.city:
              try:
                self.city = self.institution.city
              except:
                pass
            if not self.state:
              try:
                if self.institution.state.__len__() < 7:
                  self.state = self.institution.state
              except:
                pass
            if not self.country:
              try:
                self.country = self.institution.country
              except:
                pass
            # hacky data cleaning
            if self.country == "United States" or "USA":
              self.country = "United States of America"
            if self.city and self.state:
              # geolocate lat and long
              g = geocoders.GoogleV3()
              location = "%s %s" % (self.city, self.state)
              try:
                place, (lat, lng) = g.geocode(location)
                self.latitude = lat
                self.longitude = lng
              except:
                # try for multiple locations
                try:
                  for place, (lat, lng) in g.geocode(location, exactly_one=False):
                    self.latitude = lat
                    self.longitude = lng
                except:
                  pass
              
            super(AcademicProgram, self).save()

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "academic program"

class ProgramType(models.Model):
    name = models.CharField(_('type name'), max_length=255)
    slug = models.CharField(_('type code'), max_length=100)
    
    def __unicode__(self):
        return self.name

    

rc/resources/apps/greenfunds/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.contrib.contenttypes.generic import generic_inlineformset_factory
from models import GreenFund, StudentFeeFund, DonationFund, DepartmentFund, HybridFund
from aashe.organization.models import Organization

class StudentFeeFundCreateForm(forms.ModelForm):

      class Meta:
          model = StudentFeeFund

class DonationFundCreateForm(forms.ModelForm):

      class Meta:
          model = DonationFund

class DepartmentFundCreateForm(forms.ModelForm):

      class Meta:
          model = DepartmentFund

class HybridFundCreateForm(forms.ModelForm):

      class Meta:
          model = HybridFund

class GreenFundUpdateForm(forms.ModelForm):

    class Meta:
        # model = RevolvingLoanFund
        exclude = ('object_id')

rc/resources/apps/policies/forms.py
from django import forms
from rc.resources.apps.policies.models import Policy


class PolicyForm(forms.ModelForm):
    class Meta:
        model = Policy
    

rc/resources/apps/revolving_fund/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from models import RevolvingLoanFund
from aashe.organization.models import Organization


class RevolvingLoanFundUpdateForm(forms.ModelForm):
    description = forms.CharField(required=False, widget=PagedownWidget)
    contact_first_name = forms.CharField(required=True)
    contact_last_name = forms.CharField(required=True)
    contact_email = forms.CharField(required=True)    
    
    class Meta:
        model = RevolvingLoanFund
        exclude = ('institution', 'slug', 'total_funds_date',
                   'published', 'pub_date', 'last_updated')

class RevolvingLoanFundCreateForm(forms.ModelForm):
    institution = forms.ModelChoiceField(
        queryset=Organization.objects.filter(sector='Campus'))
    description = forms.CharField(required=False, widget=PagedownWidget)
    contact_first_name = forms.CharField(required=True)
    contact_last_name = forms.CharField(required=True)
    contact_email = forms.CharField(required=True)
    
    class Meta:
        model = RevolvingLoanFund
        exclude = ('slug', 'total_funds_date', 'published', 'pub_date',
                   'last_updated')

rc/cms/views.py
from django.shortcuts import render_to_response
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.template import RequestContext
from rc.cms.models import Page

class PageView(DetailView):
    queryset = Page.objects.published()
    slug_field = 'path'

    def get_context_data(self, **kwargs):
        context = super(PageView, self).get_context_data(**kwargs)
        return context

rc/resources/apps/officers/views.py
from django.views.generic.list import ListView
from rc.resources.apps.officers.models import *
from rc.resources.views import ResourceItemListView

class OfficerList(ResourceItemListView):
    allow_empty = True
    model = CampusSustainabilityOfficer
    queryset = CampusSustainabilityOfficer.objects.order_by('organization__picklist_name')

rc/resources/apps/pae/views.py
from rc.resources.views import ResourceItemListView
from rc.resources.apps.pae.models import StudentFeesDescription, StudentFee

class StudentFeeListView(ResourceItemListView):

    def get_context_data(self, **kwargs):
        '''StudentFees are displayed by institution, and preceeded by
        some text that's stored in a StudentFeesDescription record.
        The 'matched_descriptions' and 'unmatched_fees' elements added
        to context_data can be used in a template, rather than object_list.
        '''
        context = super(StudentFeeListView, self).get_context_data(**kwargs)

        matched_descriptions = list()
        for descr in StudentFeesDescription.objects.exclude(
                organization__isnull=True).order_by('organization__name'):
            fees = StudentFee.objects.filter(
                organization=descr.organization).order_by('title')
            matched_descriptions.append({ 'description': descr.description,
                                          'organization': descr.organization,
                                          'fees': fees })
        context['matched_descriptions'] = matched_descriptions

        context['unmatched_fees'] = StudentFee.objects.filter(
            organization__isnull=True).order_by('title')

        return context

rc/templates/academic_programs/ap_browse.html
{% extends "academic_programs/base_programs.html" %}

{% block content %}

    <h1>
      {% block title %}
        {{ title }}
      {% endblock title %}
    </h1>

    <div class="content clear-block">

    {% if member_only %}
	  <div id="restricted-text" class="accessible">
	    You are viewing member-only content.
	  </div>
    {% endif %}

    {% if request.user.is_authenticated %}
          <div id="admin-controls" style="background-color: #ddd;">
            <p style="padding: 2px;">Admin controls: <a href="{{ admin_changelist_url }}">Edit in Admin</a></p>
          </div>
    {% endif %}
    
    <h2>Academic Programs</h2>
    <table class="views-items academic-programs">
      {% for program in object_list %}
      <tr>
        <th>Title</th>
        <th>Type</th>
        <th>Distance or Local</th>
        <th>Institution(s)</th>
        <th>Program Discipline</th>
        <th>Location</th>
      </tr>
      
              <tr>  
      <td class="title">
        <a href="changme">{{ program.title }}</a>
      </td>

      <td class="field-program-type-value">
        {{ program.program_type.name }}
      </td>

      <td class="field-program-distance-value">
        {{ program.distance_ed }}
      </td>

      <td class="field-campus-value">
        {% for org in program.organization %}
          {{ org.name }}
        {% endfor %}
      </td>

      <td class="field-program-discipline-value">
          {{ program.discipline }}
      </td>

      <td class="phpcode">
        {% for org in program.organization %}
          {{ org.city }}, {{ org.province }}
        {% endfor %}
      </td>

      <td class="view-node">
       <a href="changme">Program Overview</a>
      </td>

      <td class="field-program-url-url">
      <a href="{{ program.homepage }}">Link to Program</a>
      </td>
      
    </tr>
    {% endfor %}
    </table>
    
     {% if is_paginated %}
       <div class="pagination">
         <span class="step-links">
           {% if page_obj.has_previous %}
           <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
           {% endif %}

           <span class="current">
             Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
           </span>

           {% if page_obj.has_next %}
           <a href="?page={{ page_obj.next_page_number }}">Next</a>
           {% endif %}
         </span>
       </div>
    {% endif %}
  
    {% block body %}
	  {% endblock body %}

    <div id="content-footer">
      <div class="block block-block " id="block-block-43">
        <div class="block-content content">
          <p>
		    <em>Please email <a href="mailto:resources@aashe.org">
                resources@aashe.org</a> with any suggestions, additions or
		        updates.
		    </em>
		  </p>
        </div>
      </div>
    </div><!-- #content-footer -->

  </div><!-- .content.clear-block -->

{% endblock %}

rc/templates/academic_programs/ap_crud_success.html
{% extends "academic_programs/base_programs.html" %}

{% block title %}Thank You!{% endblock %}

{% block breadcrumb %}
<ul>
{{ block.super }}
<li class="last">Add an Academic Program</li>
</ul>
{% endblock breadcrumb %}

{% block page-title %}
<h1 class="page-title">Add an Academic Program</h1>
{% endblock %}

{% block content %}
<p><a href="{% url program-index-view %}">Back to Academic Programs</a></p>

<p>Your submission has been received!</p>

<p>Thank you for helping to improve this resource. We have received your submission and will review the information before publishing it to the AASHE resource center. If you have any questions or comments please contact <a href="mailto:resources@aashe.org">resources@aashe.org</a>.</p>

{% endblock content %}

rc/templates/academic_programs/ap_detail.html
{% extends "academic_programs/base_programs.html" %}

{% block content %}

{% if user.is_staff %}
<p><a href="{% url admin:academic_programs_academicprogram_change object.pk %}">Edit in Admin</a></p>
{% else %}
<p><a href="{% url program-edit slug=object.slug %}">Edit this Program</a></p>
{% endif %}


<h1>
  {% block title %}
    {{ object.title }}
  {% endblock title %}
</h1>

{% if object.institution %}
<h2>{{ object.institution.name }}</h2>
{% endif %}  
  
<table>
<tbody>
<tr>
	<th>Program Description</th>
	<th>Information</th>
</tr>

{% if object.city and object.state %}
  <tr><td>Program Location</td><td>{{ object.city }}, {{ object.state }}</td></tr>
{% endif %}
  
<tr><td>Program Type</td><td>{{ object.program_type.name }}</td></tr>

{% if object.discipline %}
  <tr><td>Program Discipline</td><td>{{ object.discipline }}</td></tr>
{% endif %}

{% if object.founded %}
  <tr><td>Year Founded</td><td>{{ object.founded }}</td></tr>
{% endif %}

{% if object.duration %}
  <tr><td>Program Duration</td><td>{{ object.duration }}</td></tr>
{% endif %}

{% if object.language %}
  <tr><td>Program Language of Instruction</td><td>{{ object.language }}</td></tr>
{% endif %}

{% if object.department %}
  <tr><td>Program Department</td><td>{{ object.department }}</td></tr>
{% endif %}

{% if object.distance_ed %}
  <tr><td>Local or Distance-Education?</td><td>{{ object.get_distance_ed_display }}</td></tr>
{% endif %}

{% if object.commitment %}
  <tr><td>Full-time or Part-time?</td><td>{{ object.get_commitment_display }}</td></tr>
{% endif %}
  
{% if object.homepage %}
  <tr><td>Program Homepage</td><td><a href="{{ object.homepage }}">Link</a></td></tr>
{% endif %}

{% if object.blog %}
  <tr><td>Program Blog</td><td><a href="{{ object.blog }}">Link</a></td></tr>
{% endif %}

{% if object.linkedin %}
  <tr><td>Program LinkedIn</td><td><a href="{{ object.linkedin }}">Link</a></td></tr>
{% endif %}

{% if object.facebook %}
  <tr><td>Program Facebook</td><td><a href="{{ object.facebook }}">Link</a></td></tr>
{% endif %}

{% if object.twitter %}
  <tr><td>Program Twitter</td><td><a href="{{ object.twitter }}">Link</a></td></tr>
{% endif %}

<tr>
  <td>Program Contact</td><td>{{ object.project_contact1_details|default:"Data Not Provided" }}</td>
</tr>

</tbody>
</table>

{% if object.description %}
<h2>Program Description</h2>

{% autoescape off %}
<p>{{ object.description }}</p>
{% endautoescape %}

{% endif %}


<h2>Additional Links</h2>
<p>

{% if object.discipline %}
<a href='{% url program-discipline-view discipline=object.discipline.slug %}'>View Other {{ object.discipline }} Programs</a><br />
{% endif %}
<a href='{% url program-type-view type=object.program_type.slug %}'>View Other {{ object.program_type.name }} Programs</a><br />
<a href='{% url program-index-view %}'>Return to Academic Programs Search Page</a><br /></p>


{% endblock content %}

rc/templates/academic_programs/ap_index.html
{% extends "academic_programs/base_programs.html" %}

{% block page-title %}
<h1 class="page-title">AASHE Academic Programs Database</h1>
{% endblock %}

{% block breadcrumb %}
{{ block.super }}
</ul>
{% endblock breadcrumb %}

{% block content %}
<div class="resource-head">
  <p>AASHE's Academic Program database contains <strong>{{ total_programs }}</strong> sustainability-focused academic programs at <strong>{{ total_campuses }}</strong> campuses in <strong>{{ total_states }}</strong> states and provinces.</p>
</div>

<div class="program-index-block clearfix">
  <div class="program-nav-block-left">
    <h2>Search</h2>
    <form class="program-form" method="get" action="{% url academic-program-search %}">{% csrf_token %}<input name="q" type="text" />        
    <div class="search-buttons">
      <input id="first-submit" class="form-submit" type="submit" value="Search">
    </div>
    </form>
    <p class="program-small">Searches institution name, city, state, program name, program type, discipline fields.</p>
  </div>

  <div class="program-nav-block-right">
    <h2>Browse By</h2>
       <div class="tab-wrapper">
         <div class="program-nav-tabs"><a href="#types">Degree Types</a><a href="#disciplines">Disciplines</a></div>
         <div id="types" class="tab">
         <ul class="nav-menu">
         {% for program_type in types %}
           <li><a href="{% url program-type-view type=program_type.slug %}">{{ program_type.name }}</a></li>
         {% endfor %}
         </ul>
         </div>
         <div id="disciplines" class="tab">
         <ul class="nav-menu">
           {% for discipline in disciplines %}
           <li><a href="{% url program-discipline-view discipline=discipline.slug %}">{{ discipline.name }}</a></li>
           {% endfor %}
         </ul>
         </div>
     </div>
  </div>
</div>

<div class="program-index-block clearfix">
  <div class="program-nav-block-left program-nav-block-bottom">
    <h2>Contribute</h2>
    <p><strong>Update Programs</strong> &mdash; click the <em>Update this Information</em> link on an existing program to submit additional information.</p>
    <p><strong>Add a Program</strong> &mdash; use the <a href="{% url program-add %}">Add an Academic Program</a> form to submit a missing program.</p>
    <p><strong>Conduct Analysis</strong> &mdash; let us know at <a href="mailto:resources@aashe.org">resources@aashe.org</a> if you have published or are working on analysis that draws on the database.</p>
  </div>

  <div class="program-nav-block-right program-nav-block-bottom">
    <h2>Analysis</h2>
    <ul class="program-nav-list">
      <li><a href="map">Program Map</a></li>
      <li>Charts (Coming Soon)</li>
    </ul>
  </div>
</div>

{% endblock content %}

rc/templates/academic_programs/ap_index_old.html
{% extends "academic_programs/base_programs.html" %}

{% block page-title %}
<h1 class="page-title">AASHE Academic Programs Database</h1>
{% endblock %}

{% block breadcrumb %}
{{ block.super }}
</ul>
{% endblock breadcrumb %}

{% block content %}
<div class="resource-head">
  
  <p>AASHE's Academic Program database contains <strong>x</strong> sustainability-focused academic programs at <strong>x</strong> campuses in <strong>x</strong> states and provinces.</p>
  
  <div id="sponsorship-home" class="clearfix">
    <a href="changme">

    <div id="sponsorship-home-left" style="display: block; float: right; width: 400px; position: relative; top: 25px;">
      <p>This database made possible through the sponsorship of AMSOLAR. If you have questions about implementing a solar project on your campus, <span style="color: #004d72; text-decoration: underline;">AMSOLAR is available to answer your questions.</span></p>
    </div>
    
    <div style="width: 200px;">
      <img id="sponsorship-homepage-logo" src="http://conf2011.aashe.org/index.php?q=files/imagecache/silver_sponsor/WasteManagement_logo_0.png">
    </div>
    </a>
  </div>

</div>

<div class="program-index-block clearfix">
  <div class="program-nav-block-right">
    <h2>Search</h2>
    <form class="changme" method="get" action="{% url academic-program-search %}">{% csrf_token %}<input name="q" type="text" /><input type="submit" value="Search" /></form>
  </div>

  <div class="program-nav-block-left">
    <div class="accordion-wrapper">
      <div class="accordionButton on first"><h3><a href="#">Degree Types</a></h3></div>
      <div class="accordionContent">
      <ul class="nav-menu">
      {% for program_type in types %}
        <li><a href="{% url program-type-view type=program_type.slug %}">{{ program_type.name }}</a></li>
      {% endfor %}
      </ul>
      </div>
      
      <div class="accordionButton"><h3><a href="#">Disciplines</a></h3></div>
      <div class="accordionContent">
      <ul class="nav-menu">
        <ul class="nav-menu">
        {% for discipline in disciplines %}
        <li><a href="{% url program-discipline-view discipline=discipline.slug %}">{{ discipline.name }}</a></li>
        {% endfor %}
      </ul>
      </div>
      
      <div class="accordionButton"><h3><a href="#">Contribute</a></h3></div>
      <div class="accordionContent">
      <ul class="nav-menu">      
      <li><a href="changme">Update Information</a></li>
      <li><a href="changme">Add a Program</a></li>
      <li><a href="changme">Provide Feedback</a></li>
      </ul>
      </div>
      
      <div class="accordionButton"><h3><a href="#">Explore</a></h3></div>
      <div class="accordionContent">
      <ul class="nav-menu">
      <li><a href="changme">View Statistics</a></li>
      <li><a href="changme">Get Data</a></li>
      </ul>
      </div>
      
  </div>
  </div>
  
  <div class="program-sponsors-block">
    <p>Please visit our sponsors:</p>
    <div class="sponsor">
          <img src="http://conf2011.aashe.org/index.php?q=files/imagecache/silver_sponsor/Aramark%20without%20background.png" />
        </div>
        <div class="sponsor">
          <img src="http://conf2011.aashe.org/index.php?q=files/imagecache/silver_sponsor/WasteManagement_logo_0.png" />
        </div>
        <div class="sponsor">
          <img src="http://conf2011.aashe.org/index.php?q=files/imagecache/silver_sponsor/siemens_logo_rgb_1.jpg" />
        </div>
        <div class="sponsor">
          <img src="http://conf2011.aashe.org/index.php?q=files/imagecache/silver_sponsor/Trane.png" />
        </div>
      </div>
  
</div>

{% endblock %}