rc/cms/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.base import TemplateView
from rc.cms.views import PageView

urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='cms/index.html'),
        name='resource-center-index'),
    url(r'^(?P<slug>.+)/$', PageView.as_view()),
    )

rc/resources/apps/officers/urls.py
from django.conf.urls.defaults import patterns, url
from rc.resources.apps.officers.models import *
from rc.resources.apps.officers.views import *

urlpatterns = patterns('',
    # url(r'^directory-campus-sustainability-officers$', OfficerList.as_view(template_name = 'officers/directory.html'), name="officers-directory"),
   url(r'^directory-campus-sustainability-officers$',
       ResourceItemListView.as_view(
           model=CampusSustainabilityOfficer,
           queryset=CampusSustainabilityOfficer.objects.order_by(
                   'organization__name')),
       name='officer-directory',
       kwargs={'member_only': True}),
    )

rc/resources/apps/pae/urls.py
from django.conf.urls.defaults import patterns, url

from rc.resources.views import ResourceItemListView
from rc.resources.apps.pae import models
from rc.resources.apps.pae.views import StudentFeeListView


urlpatterns = patterns('',

    url(r'^alumni-sustainability-funds$',
        ResourceItemListView.as_view(
            model=models.AlumniFund,
            queryset=models.AlumniFund.objects.published().order_by('organization__name')),
        name='alumni-funds',
        kwargs={'member_only': True}),

    url(r'^master-plans-incorporate-sustainability$',
        ResourceItemListView.as_view(
            model=models.MasterPlan,
            queryset=models.MasterPlan.objects.published().order_by(
                    'minor_reference_only', 'organization__name')),
        name='master-plans',
        kwargs={'member_only': True, 'title': 'Campus Master Plans that Incorporate Sustainability'}),

    url(r'^campus-sustainability-assessment-tools$',
        ResourceItemListView.as_view(
            model=models.AssessmentTool,
            queryset=models.AssessmentTool.objects.published().order_by(
                    'provider', 'organization__name')),
        name='assessment-tools',
        kwargs={'member_only': True,
         'type_list': dict(models.AssessmentTool.CREATORS)}),

    url(r'^campus-sustainability-blogs$',
        ResourceItemListView.as_view(
            model=models.SustainabilityBlog,
            queryset=models.SustainabilityBlog.objects.published().order_by(
                    'type', 'title')),
        name='sustainability-blogs',
        kwargs={'member_only': True}
        ),

    url(r'^campus-sustainability-plans$',
        ResourceItemListView.as_view(
            model=models.SustainabilityPlan,
            queryset=models.SustainabilityPlan.objects.published().order_by(
                    'organization__name')),
        name='sustainability-plans',
        kwargs={'member_only': True}),

    # url(r'^campus-sustainability-revolving-loan-funds',
    #     ResourceItemListView.as_view(
    #         model=models.RevolvingLoanFund,
    #         queryset=models.RevolvingLoanFund.objects.published().order_by(
    #                 'organization__name', 'title')),
    #     name='revolving-loan-funds',
    #     kwargs={'title': 'Campus Sustainability Revolving Loan Funds',
    #             'member_only': True}),

    url(r'^mandatory-student-fees-renewable-energy-and-energy-efficiency$',
        StudentFeeListView.as_view(
            model=models.StudentFeesDescription,
            queryset=models.StudentFee.objects.published().order_by(
                    'organization__name')),
        name='student-fees',
        kwargs={
            'member_only': True,
            'title': 'Dedicated Student Fees for Sustainability'}
    ),

    )

rc/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from aashe import moderation
from aashe.aasheauth.forms import LoginForm


admin.autodiscover()

moderation.auto_discover()

urlpatterns = patterns(
    '',
    (r'^admin/linkcheck/', include('linkcheck.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^moderation/', include('aashe.moderation.urls')),
    url(r'^campus-sustainability-revolving-loan-funds/',
        include('rc.resources.apps.revolving_fund.urls')),
    url(r'^accounts/login/$', 'aashe.aasheauth.views.login',
        {'template_name': 'auth/login.html',
         'authentication_form': LoginForm},
        name='accounts-login'),
    url(r'^accounts/logout/$', 'aashe.aasheauth.views.logout_then_login',
        {'login_url': reverse_lazy('accounts-login')},
        name='accounts-logout'),
    url(r'^academic-programs/', include('rc.resources.apps.academic_programs.urls')),
    url(r'^green-funds/', include('rc.resources.apps.greenfunds.urls')),
    ('', include('rc.resources.apps.education.urls')),
    ('', include('rc.resources.apps.operations.urls')),
    ('', include('rc.resources.apps.pae.urls')),
    ('', include('rc.resources.apps.policies.urls')),
    ('', include('rc.resources.apps.programs.urls')),
    ('', include('rc.resources.apps.officers.urls')),
    ('', include('rc.cms.urls')),    
)

rc/resources/models.py
import imp
from django.conf import settings

from datetime import datetime
from gettext import gettext as _

from django.db import models

from aashe.organization.models import Organization

from django.utils.importlib import import_module



class ResourceItemManager(models.Manager):
    def published(self):
        return self.filter(published=True)


class ResourceItem(models.Model):
    '''
    Abstract base-class to support commonality between all resources
    in the the resource center.
    '''
    title = models.CharField(_('resource title'), max_length=256)
    url = models.URLField(_('resource url'), blank=True, max_length=256)
    organization = models.ForeignKey(Organization, blank=True, null=True)
    description = models.TextField(_('resource description'), blank=True)
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    updated_date = models.DateTimeField(auto_now=True, editable=False)
    published = models.BooleanField(_('published'), default=True)
    pub_date = models.DateTimeField(editable=False)
    notes = models.TextField(_('internal notes'), blank=True)
    objects = ResourceItemManager()

    class Meta:
        abstract = True

    def save(self):
        if self.published and not self.pub_date:
            self.pub_date = datetime.now()
        elif not self.published:
            self.pub_date = None
        super(ResourceItem, self).save()

    def __unicode__(self):
        if self.title:
            return self.title
        else:
            return u'<%s: %s>' % (self.__class__.__name__, self.pk)

rc/resources/apps/greenfunds/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.contrib.contenttypes.generic import generic_inlineformset_factory
from models import GreenFund, StudentFeeFund, DonationFund, DepartmentFund, HybridFund
from aashe.organization.models import Organization

class StudentFeeFundCreateForm(forms.ModelForm):

      class Meta:
          model = StudentFeeFund

class DonationFundCreateForm(forms.ModelForm):

      class Meta:
          model = DonationFund

class DepartmentFundCreateForm(forms.ModelForm):

      class Meta:
          model = DepartmentFund

class HybridFundCreateForm(forms.ModelForm):

      class Meta:
          model = HybridFund

class GreenFundUpdateForm(forms.ModelForm):

    class Meta:
        # model = RevolvingLoanFund
        exclude = ('object_id')

rc/resources/apps/policies/forms.py
from django import forms
from rc.resources.apps.policies.models import Policy


class PolicyForm(forms.ModelForm):
    class Meta:
        model = Policy
    

rc/resources/apps/revolving_fund/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from models import RevolvingLoanFund
from aashe.organization.models import Organization


class RevolvingLoanFundUpdateForm(forms.ModelForm):
    description = forms.CharField(required=False, widget=PagedownWidget)
    contact_first_name = forms.CharField(required=True)
    contact_last_name = forms.CharField(required=True)
    contact_email = forms.CharField(required=True)    
    
    class Meta:
        model = RevolvingLoanFund
        exclude = ('institution', 'slug', 'total_funds_date',
                   'published', 'pub_date', 'last_updated')

class RevolvingLoanFundCreateForm(forms.ModelForm):
    institution = forms.ModelChoiceField(
        queryset=Organization.objects.filter(sector='Campus'))
    description = forms.CharField(required=False, widget=PagedownWidget)
    contact_first_name = forms.CharField(required=True)
    contact_last_name = forms.CharField(required=True)
    contact_email = forms.CharField(required=True)
    
    class Meta:
        model = RevolvingLoanFund
        exclude = ('slug', 'total_funds_date', 'published', 'pub_date',
                   'last_updated')

rc/cms/views.py
from django.shortcuts import render_to_response
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.template import RequestContext
from rc.cms.models import Page

class PageView(DetailView):
    queryset = Page.objects.published()
    slug_field = 'path'

    def get_context_data(self, **kwargs):
        context = super(PageView, self).get_context_data(**kwargs)
        return context

rc/resources/apps/academic_programs/views.py
from django.http import Http404
from django.core.urlresolvers import reverse 
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from aashe.disciplines.models import Discipline
from django.shortcuts import get_object_or_404, render_to_response
from django.views.generic.edit import CreateView, UpdateView, FormView
from haystack.views import SearchView, search_view_factory
from rc.resources.apps.academic_programs.models import *
from rc.resources.apps.academic_programs.forms import *
from django.core.paginator import InvalidPage, EmptyPage #, Paginator
from rc.resources.apps.academic_programs.digg_paginator import DiggPaginator as Paginator

class ProgramList(ListView):
    allow_empty = True
    model = AcademicProgram
    paginate_by = 50
    
class ProgramMap(ListView):
    queryset = AcademicProgram.objects.filter(published=True)
    
class ProgramIndex(ListView):
    queryset = AcademicProgram.objects.filter(published=True)
            
    def get_context_data(self, **kwargs):
        context = super(ProgramIndex, self).get_context_data(**kwargs)
        # Check if disciplines have programs
        disciplines = Discipline.objects.all()
        final_disciplines = []
        for discipline in disciplines:
          program_count = AcademicProgram.objects.filter(discipline=discipline).count()
          if program_count > 0:
            final_disciplines.append(discipline)
          else:
            pass
        
        # Add disciplines to context
        context['disciplines'] = final_disciplines
        
        # Check if types have programs
        program_types = ProgramType.objects.all()
        final_types = []
        for program_type in program_types:
          program_count = AcademicProgram.objects.filter(program_type=program_type).count()
          if program_count > 0:
            final_types.append(program_type)
          else:
            pass
        # Add program types to context
        context['types'] = final_types
        
        context['total_programs'] = AcademicProgram.objects.filter(published=True).count()
        context['total_campuses'] = AcademicProgram.objects.filter(published=True).values('institution').distinct().count()
        context['total_states'] = AcademicProgram.objects.filter(published=True).values('state').distinct().count()
        
        return context

class ProgramTypeTable(ListView):    
    def get_queryset(self):
        if self.context_object_name == 'program_type':
            self.program_type = get_object_or_404(ProgramType, slug=self.kwargs['type'])
            return AcademicProgram.objects.filter(program_type=self.program_type)
    
    def get_context_data(self, **kwargs):
        context = super(ProgramTypeTable, self).get_context_data(**kwargs)
        try:
          context['program_type'] = ProgramType.objects.get(slug=self.kwargs['type']).name
          context['count'] = AcademicProgram.objects.filter(program_type=self.program_type).count()
          return context
        except:
          return context
      
class ProgramDisciplineTable(ListView):
  def get_queryset(self):
      if self.context_object_name == 'discipline':
          self.discipline = get_object_or_404(Discipline, slug=self.kwargs['discipline'])
          return AcademicProgram.objects.filter(discipline=self.discipline)
  
  def get_context_data(self, **kwargs):
      context = super(ProgramDisciplineTable, self).get_context_data(**kwargs)
      try:
        context['discipline'] = Discipline.objects.get(slug=self.kwargs['discipline']).name
        context['count'] = AcademicProgram.objects.filter(discipline=self.discipline).count()
        return context
      except:
        return context

class ProgramDetail(DetailView):
    queryset = AcademicProgram.objects.filter(published=True)
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context = super(ProgramDetail, self).get_context_data(**kwargs)
        return context
        
# CRUD Views
class ProgramCreateView(CreateView):
    form_class = ProgramCreateForm
    template_name = 'academic_programs/ap_create.html'

    def get_form(self, form_class):
        form = form_class(**self.get_form_kwargs())
        form.request = self.request
        return form

    def get_success_url(self):
        return reverse("program-add-success")

class ProgramUpdateView(UpdateView):
    model = AcademicProgram
    form_class = ProgramUpdateForm
    template_name = 'academic_programs/ap_update.html'

    def get_success_url(self):
        return reverse("program-edit-success")

    def get_form(self, form_class):
        form = form_class(**self.get_form_kwargs())
        form.request = self.request
        return form

# Overridden search views
class ProgramSearchView(SearchView):
    def build_page(self):
        """
        Paginates the results appropriately.

        In case someone does not want to use Django's built-in pagination, it
        should be a simple matter to override this method to do what they would
        like.
        """
        try:
            page_no = int(self.request.GET.get('page', 1))
        except (TypeError, ValueError):
            raise Http404("Not a valid number for page.")

        if page_no < 1:
            raise Http404("Pages should be 1 or greater.")

        start_offset = (page_no - 1) * self.results_per_page
        self.results[start_offset:start_offset + self.results_per_page]

        paginator = Paginator(self.results, self.results_per_page)

        try:
            page = paginator.page(page_no)
        except InvalidPage:
            raise Http404("No such page!")

        return (paginator, page)

rc/resources/apps/officers/views.py
from django.views.generic.list import ListView
from rc.resources.apps.officers.models import *
from rc.resources.views import ResourceItemListView

class OfficerList(ResourceItemListView):
    allow_empty = True
    model = CampusSustainabilityOfficer
    queryset = CampusSustainabilityOfficer.objects.order_by('organization__picklist_name')

rc/resources/apps/pae/views.py
from rc.resources.views import ResourceItemListView
from rc.resources.apps.pae.models import StudentFeesDescription, StudentFee

class StudentFeeListView(ResourceItemListView):

    def get_context_data(self, **kwargs):
        '''StudentFees are displayed by institution, and preceeded by
        some text that's stored in a StudentFeesDescription record.
        The 'matched_descriptions' and 'unmatched_fees' elements added
        to context_data can be used in a template, rather than object_list.
        '''
        context = super(StudentFeeListView, self).get_context_data(**kwargs)

        matched_descriptions = list()
        for descr in StudentFeesDescription.objects.exclude(
                organization__isnull=True).order_by('organization__name'):
            fees = StudentFee.objects.filter(
                organization=descr.organization).order_by('title')
            matched_descriptions.append({ 'description': descr.description,
                                          'organization': descr.organization,
                                          'fees': fees })
        context['matched_descriptions'] = matched_descriptions

        context['unmatched_fees'] = StudentFee.objects.filter(
            organization__isnull=True).order_by('title')

        return context

rc/templates/policies/energypolicy_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  Campus Sustainable Energy Policies
{% endblock title %}

{% block body %}

  <p>
    <div id="resource_list" class="content clear-block">
      <p>
        <table>
          <tbody>
            <tr>
              <th>Institution</th>
              <th>Energy Policy</th>
            </tr>
        {% for resource in object_list %}
          <tr>
          <td>{{ resource.organization.name }}</td>
          <td><a href="{{ resource.url }}">{{ resource.title }}</a></td>
          </tr>
        {% endfor %}
        </tbody>
        </table>
      </p>
    </div>
  </p>

{% endblock body %}

rc/templates/policies/fairtradepolicy_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  Campus Fair Trade Practices &amp; Policies
{% endblock title %}

{% block body %}

  <p>

    This resource is a list of colleges and universities in
    the US and Canada that have Fairtrade policies in place
    for purchasing goods that are certified Fairtrade for use
    in their dining facilities and campus stores. Many
    campuses in the United Kingdom also have policies in
    place. For a resource on those campuses, please visit
    <a href="http://www.internationalcounselor.org/archives/499">
    this page</a>.

  </p>

  <div id="resource_list">
    <p>
      {% regroup object_list by organization.country as countries %}

     {% for country in countries %}
       <h3>{{ country.grouper }}</h3>
       <table>
         <tbody>
           <tr>
             <th>Instititution</th>
             <th>Policy</th>
             <th>Product Types</th>
           </tr>
           {% regroup country.list by organization.name as org_list %}
           {% for org in org_list %}
             <tr>
               <td>{{ org.grouper }}</td>
               {% include "links_table_cell.html" with resources=org.list %}
               {% for resource in org.list %}
                 {% if forloop.last %}
                   {% comment %}
                     Resources not connected to an organization
                     are grouped together; doesn't make sense
                     to show the product_types for the last one in
                     that group.
                   {% endcomment %}
                   {% if resource.organization %}
                     <td>{{ resource.product_types }}</td>
                   {% endif %}
                 {% endif %}
               {% endfor %}
             </tr>
           {% endfor %}
         </tbody>
       </table>
     {% endfor %}
    </p>
  </div>

{% endblock body %}

rc/templates/policies/greenbuildingpolicy_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  Campus Building Guidelines and Green Building Policies
{% endblock title %}

{% block body %}

  <p>
    In recognition of the significant environmental and health
    impacts associated with buildings as well as the long-term cost
    savings from better design, colleges and universities are
    increasingly adopting green building policies. In many cases,
    campuses are committing to meeting standards set by the U.S
    Green Building Council's <a href="http://www.leedbuilding.org">
    LEED (Leadership in Energy and Environmental Design)</a> Green
    Building Rating System.
  </p>
  <p>
    Below is a list of campus green building policies grouped by
    LEED standard where relevant, or ordered alphabetically by
    campus in an "other" category.
  </p>
  <p>
    Users may also wish to visit the
    <a href="http://acupcc.aashe.org/statistics-tangible.php">
    ACUPCC&nbsp;Reporting System</a> which includes statistics on
    signatory campuses that have chosen to establish a policy that
    all new campus construction will be built to at least the U.S.
    Green Building Council's LEED Silver standard or equivalent.
  </p>

  <div id="resource_list">

    <p>
      {% regroup object_list by leed_level as list_by_type %}

      {% comment %}
        Sort in GreenBuildingPolicy.LEED_LEVEL order.
      {% endcomment %}
      {% for leed_level_code in type_list %}
        {% for type in list_by_type %}
          {% if type.grouper == leed_level_code %}
            {% for key, value in type_dict.items %}
              {% if key == type.grouper %}
                <h2>{{ value }}</h2>
                {% with leed_level=key %}
                  {% for resource in type.list %}
                    {% if resource.leed_level = leed_level %}
                      <p>
                        <strong>{{ resource.organization.name }}</strong> -
                        <a href="{{ resource.url }}">{{ resource.title }}</a>
                        <br/>
                        {{ resource.description }}
                      </p>
                    {% endif %}
                  {% endfor %}
                {%endwith%}
              {% endif %}
            {% endfor %}
          {% endif %}
        {% endfor %}
      {% endfor %}

      {% comment %}
        Put the ones w/o a specified leed_level at the end.
      {% endcomment %}
      {% for type in list_by_type %}
        {% if type.grouper == "" %}
          <h2>Other Standards and Guidelines</h2>
          {% for resource in type.list %}
            <p>
              <strong>{{ resource.organization.name }}</strong> -
              <a href="{{ resource.url }}">{{ resource.title }}</a>
              <br/>
              {{ resource.description }}
            </p>
          {% endfor %}
        {% endif %}
      {% endfor %}

    </p>
  </div>

{% endblock body %}

rc/templates/policies/policy_by_country_by_org_name_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  {{ page_title|title }}    
{% endblock title %}  

{% block body %}

  <div id="opening_text">

    This resource lists campus stormwater policies and procedures that
    exist independently of water conservation policies, which can be
    found within general
    <a href="/resources/campus-water-conservation-policies">Campus
    Water Conservation Policies</a>.

  </div>

  <div id="resource_list">
    <p>
     {% regroup object_list by organization.country as country_list %}

     {% for country in country_list %}
       <h2>{{ country.grouper }}</h2>
       <table>
         <tbody>
           <tr>
             <th>Institution</th>
             <th>Policy</th>
           </tr>
           {% for resource in country.list %}
             <tr>
               <td>{{ resource.organization.name }}</td>
               <td><a href="{{ resource.url }}">{{ resource.title }}</a>
               {{ resource.notes }}
               </td>
             </tr>
           {% endfor %}
         </tbody>
       </table>
     {% endfor %}
    </p>
  </div>

{% endblock body %}

rc/templates/policies/policy_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  {{ page_title|title }}
{% endblock title %}

{% block body %}

  <div id="opening_text">
  </div>

  <p>
    <div id="resource_list" class="content clear-block">
      <p>
        {% for resource in object_list %}
            {% if with_description %}
              <p>
            {% endif %}
            <strong>{{ resource.organization.name }}</strong> -
            <a href="{{ resource.url }}">{{ resource.title }}</a>
            {% if resource.notes %}
              {{ resource.notes }}
            {% endif %}
            <br/>
            {% if with_description %}
              {{ resource.description }}
              </p>
            {% endif %}
        {% endfor %}
      </p>
    </div>
  </p>

{% endblock body %}

rc/templates/policies/policy_table_by_country_by_org_name_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  {{ page_title|title }}
{% endblock title %}

{% block body %}

  <p>
    {{ opening_text|safe }}
  </p>

  <div id="resource_list">
    <p>
     {% regroup object_list by organization.country as countries %}

     {% for country in countries %}
       <h2>{{ country.grouper }}</h2>
       <table>
         <tbody>
           <tr>
             <th>Institution</th>
             <th>Policy</th>
           </tr>
          {% include "table_rows.html" with resources=country.list %}
         </tbody>
       </table>
     {% endfor %}
    </p>
  </div>

{% endblock body %}

rc/templates/policies/policy_table_by_org_name_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  {{ page_title|title }}
{% endblock title %}

{% block body %}

  <p>
    {% if opening_text %}
      {{ opening_text }}
    {% endif %}
  </p>

  <div id="resource_list">
    <p>
     <table>
       <tbody>
         <tr>
           <th>Institution</th>
           <th>Policy</th>
         </tr>
         {% include "table_rows.html" with resources=object_list %}
       </tbody>
     </table>
    </p>
  </div>

{% endblock body %}

rc/templates/policies/policy_text_by_category_by_org_name_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  {{ page_title|title }}
{% endblock title %}

{% block body %}

  <div id="resource_list">

    <p>
      {% regroup object_list by category as list_by_type %}

      {% for type in list_by_type %}
        <p>
          <h2>{{ type.grouper }}</h2>
          {% for resource in type.list %}
            {{ resource.organization.name }} -
            <a href="{{ resource.url }}">{{ resource.title }}</a>
            <br/>
          {% endfor %}
        {% endfor %}
      </p>
    </p>
  </div>

{% endblock body %}

rc/templates/policies/policy_text_by_org_name_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  {{ page_title|title }}
{% endblock title %}

{% block body %}

  <p>
    <div id="resource_list" class="content clear-block">
      <p>
        {% for resource in object_list %}
            {% if with_description %}
              <p>
            {% endif %}
            {% if bold_org_name %}
              <strong>
            {% endif %}
            {{ resource.organization.name }}
            {% if bold_org_name %}
              </strong>
            {% endif %}
            -
            <a href="{{ resource.url }}">{{ resource.title }}</a>
            <br/>
            {% if with_description %}
              {{ resource.description }}
              </p>
            {% endif %}
        {% endfor %}
      </p>
    </div>
  </p>

{% endblock body %}

rc/templates/policies/policy_text_list_by_org_name.html
{% extends "resourceitem_list.html" %}

{% block title %}
  {{ page_title|title }}
{% endblock title %}

{% block body %}

  <div id="opening_text">
  </div>

  <p>
    <div id="resource_list" class="content clear-block">
      <p>
        {% for resource in object_list %}
            {% if with_description %}
              <p>
            {% endif %}
            <strong>{{ resource.organization.name }}</strong> -
            <a href="{{ resource.url }}">{{ resource.title }}</a>
            {% if resource.notes %}
              {{ resource.notes }}
            {% endif %}
            <br/>
            {% if with_description %}
              {{ resource.description }}
              </p>
            {% endif %}
        {% endfor %}
      </p>
    </div>
  </p>

{% endblock body %}

rc/templates/policies/responsibleinvestmentpolicy_list.html
{% extends "resourceitem_list.html" %}

{% block title %}
  Socially Responsible Investment Policies
{% endblock title %}

{% block body %}

  <p>

    This resource highlights colleges and universities that have
    adopted formal policies or guidelines on responsible
    investment. Such policies can help institutions ensure that their
    investment practices align with and advance their commitments to
    sustainability.

  </p>

  <div id="resource_list">
    <p>
      {% regroup object_list by investment_type as types %}
      {% for type in types %}
        <h2>{{ type.grouper }}</h2>
        <table>
          <tbody>
            <tr>
              <th>Institution</th>
              <th>Investment</th>
            </tr>
            {% include "table_rows.html" with resources=type.list %}
          </tbody>
        </table>
      {% endfor %}
    </p>
  </div>

{% endblock body %}